# バージョンを指定
version: '3'
# サービス定義
services:
  image: ubuntu
  ports:
    - "80:80"
    networks
    - webnet
    
  redis:
  image: redis
  networks:
    - webnet

# ネットワーク定義
networks:
 webnet:
# データボリューム定義
volumes:
 data-volume:
